### ISSUE TITLE
Not a valid country code

### ISSUE THREAD

**Issue by utkarsh2k2** [sonata-project/ecommerce#389]
While trying to enter the address details when I try to enter the country code, it says not a valid country code. There are only 2 options available to select from the dropdown - FR and GB

**Comment by pixel-paul** [comment]
This appears to be because of a bug in the getBasketDeliveryCountries() function in src/BasketBundle/Form/AddressType.php and src/CustomerBundle/Form/Type/AddressType.php. The form expects a value but gets the title, e.g. 'United Kingdom' instead of 'GB' as they are the wrong way around.

Quick fix is to change vendor/sonata-project/ecommerce/src/BasketBundle/Form/AddressType.php line 169 to:

    `$countries[Intl::getRegionBundle()->getCountryName($code)] = $code;`

and change vendor/sonata-project/ecommerce/src/CustomerBundle/Form/Type/AddressType.php line 130 to:

    `$countries[Intl::getRegionBundle()->getCountryName($code)] = $code;`

I am trying to figure out how to override the FormType.php file to avoid modification of the vendor file in the meantime: ref #399
