### ISSUE TITLE
Missing property error ($productCollection) caused by the ProductExtension

### ISSUE THREAD

**Issue by jeroendk** [sonata-project/ecommerce#644]
#### Sonata packages

```
$ composer show --latest 'sonata-project/*'
# Put the result here.
```
sonata-project/classification-bundle     3.9.2  3.10.0 Symfony SonataClassificationBundle
sonata-project/ecommerce                 3.2.2  3.2.2  E-Commerce solution provided by Sonata

## Subject
In this pull request: https://github.com/sonata-project/ecommerce/pull/585
@quisse added a fix for a missing relation. However, if I understand it correctly this requires you to add the property "productCollection" to your Collection entity.
```
$collector->addAssociation($config['class']['collection'], 'mapOneToMany', [
      'fieldName' => 'productCollection',
      'targetEntity' => $config['class']['product_collection'],
      'cascade' => [
          'persist',
      ],
      'mappedBy' => 'collection',
      'orphanRemoval' => false,
]);
``` 
In our project we use the Collection entity of the Classification bundle for multiple purposes. So we would rather not add a productCollection property to the generic Collection Entity. 

Did we configure it incorrectly? Or should this association be optional?

**Comment by jeroendk** [comment]
@quisse Any chance you can help me out here? Would love to provide a PR to revert it or maybe we can make it optional through config?

**Comment by quisse** [comment]
The doctrine schema validator fails when there's no relation.

> [FAIL] The entity-class App\Application\Sonata\ProductBundle\Entity\ProductCollection mapping is invalid:
>  * The association App\Application\Sonata\ProductBundle\Entity\ProductCollection#collection refers to the inverse side field App\Entity\SonataClassificationCollection#productCollection which does not exist.

IMO in your PR you could remove the association completely so that the relation is valid. (so following line  should be removed too) Or you could make this relation optional (one way or another).
https://github.com/sonata-project/ecommerce/blob/4b6bd488d5e69782ed26372271b661ae285906ce/src/ProductBundle/DependencyInjection/SonataProductExtension.php#L201
I'm not sure if this is possible but to me it seems that this should be solved by your own DI Extension from which you clear the relationship.(but I'm not that familiar with the Dependency Injection in Symfony)

**Comment by jeroendk** [comment]
> but to me it seems that this should be solved by your own DI Extension from which you clear the relationship.
So you think it is a good thing the Ecommerce bundle forces you to add an extra property to your Collection Entity? This collection entity is from another bundle and can be used for many other things besides the Product entity right?

**Comment by quisse** [comment]
I don't think that. #585 is about an error which is thrown due to an invalid relation. The field 'productCollection' isn't created by me. I've never used a collection neither due to change of customer priorities so I don't think I can help you there. (Whats the difference between a product collection and a category?)

After some digging I've found out that the relationship already has been deleted in https://github.com/sonata-project/ecommerce/commit/81777d214de9968fdbd0f0013ebfd91a0835a877#diff-6c03ebca9553b27367a427923ead880c:
https://github.com/sonata-project/ecommerce/blob/50a5ec86e2e65a700c601cc31e25a9378407b735/src/ProductBundle/DependencyInjection/SonataProductExtension.php#L211-L228

But it got somehow (re)added. So I guess you can just remove the relationship.

@greg0ire @OskarStark @soullivaneuh do you guys maybe know what's going on here or how did this happen?

**Comment by jeroendk** [comment]
The property is not added by the bundle but the relationship is and looks for the property `productCollection`, which is not there by default.

_What's the difference between a product collection and a category_
The Sonata classification bundle provides:
Collection
Category

To put products in collections and/or categories you create a ProductCollection entity, I think this is explained in the docs.

**Comment by quisse** [comment]
Yes, I understand. The reverse relationship should’nt be there. You can remove it in a PR.
